baseURL: "https://hugo-profile.netlify.app"
languageCode: "fr"
title: "Emerick"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #- identifier: gallery
     # name: Gallery
      #title: Blog posts
      #url: /gallery
      #weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Emerick DUSHIMIRIMANA"
  description: "Consultant en cybersécurité GRC"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo_final.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Emerick Dushimirimana" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello, je suis"
    title: "Emerick,"
    subtitle: "Consultant cybersécurité GRC"
    content: "Doté d'une forte appétence pour la sécurité informatique, je mets mon savoir-faire et mon engagement au service de la protection des systèmes d'information."
    image: /images/photo-profil.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Mon cv"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-x-twitter
          url: https://x.com/dushel_emerick
        - icon: fab fa-youtube
          url: https://www.youtube.com/channel/UCrHIfZa9FwohD8LvXogNeNw
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/emerick-dushimirimana-b80415236/        
      #customIcons:
       # - icon: /fav.png
         # url: "https://example.com"

  # About
  about:
    enable: true
    title: "A propos"
    image: "/images/photo-profil.jpg"
    content: |-
      Actuellement en fin de formation de Master 2 en Cybersécurité et apprenti ingénieur en Cybersécurité GRC, j'assiste le RSSI dans la mise en place et la conformité du SMSI. 
      Je suis à la recherche d'un CDI au sein d'une entreprise dynamique et innovante, prête à relever de nouveaux défis en matière de sécurité informatique. 
    skills:
      enable: true
      title: "Mes compétences:"
      items:
        - "ISO 27001"
        - "ISO 27002"
        - "ISO 27005"
        - "EBIOS RM"
        - "TENACY"
        - "NIS2"
        - "SIEM (SPLUNK)"
        - "TENABLE NESSUS"
        - "KALI LINUX"
        - "Python"

  # Experiences
  experience:
    enable: true
    title: "Expériences"
    items:
      
      - job: "Ingénieur Cybersécurité GRC"
        company: "SBAA"
        companyUrl: "https://example.com"
        date: "Sep 2023 - present"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: En contrat d'apprentissage en tant que ing. cyber GRC.
        content: |
          Mes missions:

          - Mise en œuvre de la PSSI
          - Réalisation d’analyse de risque.
          - Réalisation des audits de sécurité interne
          - Mise en place d’un référentiel de gestion de crise
          - Mise en place du SMSI
          - Sensibilisation des utilisateurs
          - Rédaction des politiques et des procédures

      - job: "Assistant RSSI"
        company: "Viettel"
        companyUrl: "http://viettelglobal.vn/globals/cameroon-1.html"
        date: " Août 2020 - Juil 2022"
        info:
          enable: true
          content: En CDI comme Assistant RSSI.

        featuredLink:
          enable: false
          url: "http://viettelglobal.vn/globals/cameroon-1.html"
        content: |
          Mes missions:

          - Assurer le respect des engagements contractuels en sécurité, incluant la gestion de projets et les Plans d’Assurance Sécurité
          - Gestion des incidents de sécurité
          - Cartographier les risques et les non-conformités
          - Conseiller les clients et les équipes internes sur les sujets de sécurité organisationnels
          - Veille cyber
          - Réaliser des analyses de risque

      - job: "Ingénieur système et réseau"
        company: "Matrix télécom"
        companyUrl: "https://matrixtelecoms.com/"
        date: "Mars 2019 - Juin 2020"
        featuredLink:
          enable: false
          url: "https://matrixtelecoms.com/"
        content: |
          Mes missions:

          - Installer et configurer de nouveaux équipements informatiques et périphériques
          - Assister les utilisateurs
          - Gérer des pannes des équipements, des logiciels et des systèmes
          - Déployer des postes clients
          - Tenir à jour et compléter la documentation d’exploitation
          - Identifier, analyser et résoudre les problèmes de réseaux et de système
          - Effectuer une évaluation de la vulnérabilité/analyse du réseau

  # Education
  education:
    enable: true
    title: "Scolarité"
    index: false
    items:
      - title: "Master Ingénieur Systèmes, réseaux et cybersécurité"
        school:
          name: "Institut Européen de Formation en Ingénierie Informatique (IEF2I)"
          url: "https://ief2i-education.com/"
        date: "2022 - 2024"
      - title: "Ingénieur des travaux : Informatique et Réseau"
        school: 
          name: "Ecole Nationale Supérieure des Postes, des Télécoms et des TIC"
          url: "https://e-supptic.cm/"
        date: "2018 - 2021"

      - title: "Baccalauréat Scientifique"
        school:
          name: "Séminaire Saint-Paul"
          url: ""
        date: "2018"
        #GPA: "4.2 out of 5.0"
        #featuredLink:
          #enable: true
          #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: CCNA (Cisco Certified Network Associate)
        content: Avec la certification CCNA, je possède les compétences nécessaires pour configurer, administrer et dépanner des réseaux Cisco, ainsi que pour assurer la sécurité et l'optimisation des infrastructures réseau.
        #url: https://example.com
        image: /images/achievment.jpg
      - title: Microsoft Az900
        content: Avec la certification Microsoft AZ-900, je maîtrise les bases des services cloud de Microsoft Azure, ce qui me permet de comprendre et d’implémenter des solutions cloud adaptées aux besoins des entreprises.
        image: /images/achievment.jpg
      - title: Certified in Cybersécurity (ISC2), En cours
        content: La certification Certified in Cybersecurity (CC) de l’(ISC)² atteste de mes compétences fondamentales en cybersécurité, me permettant d'identifier et de gérer les risques pour protéger efficacement les systèmes d'information.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      #- title: Microsoft Imagine Runner
      #  content: We are developed a product which can help others.
      #- title: Google Summer of Code
      #  content: Contributed to a open source project.
      #  url: https://example.com

  # projects
  projects:
    enable: true
    title: "Projets"
    items:
      - title: Mise en place d'une station blanche
        content: En tant que chef de projet pour la mise en place d'une station blanche, j'ai piloté l'ensemble du projet de la conception à la livraison, en coordonnant des équipes pluridisciplinaires et en assurant une gestion efficace des ressources. J'ai mis en place des solutions sécurisées respectant les normes ISO 27001 et RGPD, tout en garantissant la livraison dans les délais et dans le respect du budget. J'ai supervisé les tests, rédigé la documentation technique, et contribué à réduire les risques de cyberattaques. Ce projet a permis d'améliorer la sécurité des données critiques et d'optimiser les processus internes.
        image: /images/projects/station blanche.png

      - title: Mise en place de Passbolt 
        content: J'ai déployé le gestionnaire de mots de passe Passbolt avec Docker sur un VPS Ionos, assurant une solution sécurisée et scalable pour la gestion des identifiants. Accessible via https://pwd.emerickdushi.fr, ce projet incluait la configuration complète du système et l'optimisation des performances via conteneurs, tout en respectant les meilleures pratiques de sécurité. Cette solution a amélioré la gestion des accès et renforcé la sécurité des données sensibles de l'équipe.
        image: /images/projects/passbolt-g.jpg
        featured:
          name: Demo
          link: https://pwd.emerickdushi.fr/

      - title: Passage de l'ISO 27002:2013 à 27002:2022 pour le plan d'assurance sécurité de l'entreprise
        content: J'ai réalisé sous la supervision de mon manager, la transition du plan d'assurance sécurité de l'entreprise de la norme ISO 27002:2013 à l'ISO 27002:2022. J'ai assuré l'analyse des nouvelles exigences, la mise à jour des contrôles de sécurité et la coordination des actions de conformité, contribuant ainsi à renforcer la sécurité de l'entreprise tout en maintenant la conformité aux standards internationaux.
        image: /images/projects/iso27002.png
    
      - title: Script de revue des droits utilisateur
        content: J'ai développé un script intégrant Bash, SQL et HTML pour automatiser la revue d'habilitation des utilisateurs. Ce script récupère tous les mots de passe dont un utilisateur est propriétaire, liste les utilisateurs avec lesquels ces mots de passe sont partagés, détaille les droits associés, et affiche l'arborescence de chaque mot de passe. Cette solution permet une vue complète et détaillée des accès et des permissions liés aux mots de passe dans l'organisation.
        image: /images/projects/iso27002.png

  #Contact
  contact:
    enable: true
    title: "Me contacter"
    content: Ma boîte de réception est toujours ouverte. Que vous ayez une question ou que vous souhaitiez simplement dire bonjour, je ferai de mon mieux pour vous répondre !
    btnName: Envoyez moi un mail ici
    btnLink: mailto:contact@emerickdushi.fr
    #formspree:
     #enable: true
      #formId: xkgnnaen # Take it from your form's endpoint, like 'https://formspree.io/f/xkgnnaen'
       #emailCaption: "Enter your email address"
       #messageCaption: "Enter your message here"
       #messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Articles recents
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "minutes de lecture"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Lire"
    toc: "Table des matières"
    copyright: "Emerick Dushimirimana. Tous droits réservés"
    pageNotFound: "Page non trouvé"
    emailText: "Découvrez ce site"

  datesFormat:
    article: "02 Jan 2006"
    articleList: "02 Jan 2006"
    articleRecent: "02 Jan 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
